main/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.owner_stuff, name='owner_stuff')
]

main/items/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new_item, name='new_item'),
    path('<int:pk>/delete/', views.delete_item, name='delete_item'),
    path('<int:pk>/edit/', views.edit_item, name='edit_item'),
    path('', views.searched_items, name='searched_items'),
]

main/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('marketplace.urls')),
    path('items/', include('items.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/marketplace/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = 'marketplace'

urlpatterns = [
    path('', views.index, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='marketplace/login.html', authentication_form=LoginForm),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

main/dashboard/models.py
from django.db import models

# Create your models here.

main/items/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=250)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['name']

    def __str__(self):
        return self.name


class Item(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField(blank=True, null=True)
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    price = models.FloatField()
    image = models.ImageField(upload_to='images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

main/marketplace/models.py
from django.db import models

# Create your models here.

main/items/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-full py-2 px-6 rounded-xl border'


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['category', 'name', 'description', 'price', 'image']
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': 'w-full h-40 rounded-xl border'
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'description', 'price', 'image', 'is_sold']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

main/marketplace/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl'


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    username = forms.CharField(widget=forms.TimeInput(attrs={
        'placeholder': 'Введіть ваше ім\'я',
        'class': INPUT_CLASSES
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Введіть вашу електронну адресу',
        'class': INPUT_CLASSES
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введіть ваш пароль',
        'class': INPUT_CLASSES
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введіть ваш пароль ще раз ',
        'class': INPUT_CLASSES
    }))


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TimeInput(attrs={
        'placeholder': 'Введіть ваше ім\'я',
        'class': INPUT_CLASSES
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введіть ваш пароль',
        'class': INPUT_CLASSES
    }))

main/dashboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from items.models import Item
from django.contrib.auth.decorators import login_required


@login_required
def owner_stuff(request):
    items = Item.objects.filter(owner=request.user)

    return render(request, 'dashboard/owner_stuff.html', {
        'items': items
    })

main/items/views.py
import random

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from .forms import NewItemForm, EditItemForm
from .models import Item, Category


def searched_items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'items/searched_items.html', {
        'items': items,
        'query': query,
        'category_id': int(category_id),
        'categories': categories
    })


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[:4]

    return render(request, 'items/detail.html', {
        'item': item,
        'related_items': related_items
    })


@login_required
def new_item(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.owner = request.user
            item.save()

            return redirect('item:detail', pk=item.pk)

    form = NewItemForm()

    return render(request, 'items/form.html', {
        'form': form,
        'title': 'New item'
    })


@login_required
def delete_item(request, pk):
    item = get_object_or_404(Item, pk=pk, owner=request.user)
    if item.image:
        item.image.delete()

    item.delete()

    return redirect('dashboard:owner_stuff')


@login_required
def edit_item(request, pk):
    item = get_object_or_404(Item, pk=pk, owner=request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.pk)

    form = EditItemForm(instance=item)

    return render(request, 'items/form.html', {
        'form': form,
        'title': 'Edit item'
    })

main/marketplace/views.py
from django.shortcuts import render, redirect
from items.models import Category, Item
from .forms import SignupForm


def index(request):
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()

    return render(request, 'marketplace/index.html', {
        'categories': categories,
        'items': items,
    })


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')

    form = SignupForm()

    return render(request, 'marketplace/signup.html', {
        'form': form
    })

main/dashboard/templates/dashboard/owner_stuff.html
{% extends 'marketplace/base.html' %}

{% block content %}
  <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Товари, які були додані вами</h2>
    <div class="grid grid-cols-3 gap-3">
      {% for item in items %}
        <div>
          <a href="{% url 'item:detail' item.pk %}">
            <div>
              {% if item.image %}
                <img src="{{ item.image.url }}" class="rounded-t-xl" alt="">
              {% else %}
                <img src="" class="rounded-t-xl" alt="Тут мало б бути зображення цього товару" style="display: inline-block;">
              {% endif %}
            </div>
            <div class="p-6 bg-white rounded-b-xl">
              <h2 class="text-xl ">{{ item.name }}</h2>
              <p class="text-gray-500">Price: {{ item.price }}</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

main/items/templates/items/detail.html
{% extends 'marketplace/base.html' %}

{% block content %}
  <div class="grid grid-cols-9 gap-6">
    <div class="col-span-7 bg-gray-100 rounded-xl">
        {% if item.image %}
            <img src="{{ item.image.url }}" class="rounded-xl m-auto" style="max-height: 680px;" alt="">
        {% else %}
            <img src="" class="rounded-t-xl" alt="Тут мало б бути зображення цього товару" style="display: block; height: 442.75px; width: 442.75px">
        {% endif %}
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <div style="min-height: 456px;">
            <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
            <p class="text-gray-700"><strong>Price: {{ item.price }} грн.</strong></p>
            <p class="text-gray-700"><strong>Seller: {{ item.owner }}</strong></p>

            {% if item.description %}
            <p class="text-gray-700"><strong>Description: {{ item.description }}</strong></p>
            {% endif %}
        </div>

        <div class="mt-6 p-6 bg-white rounded-xl">
            {% if request.user == item.owner %}
                <p>Це ваш предмет</p>
                <a href="{% url 'item:edit_item' item.pk %}" class="inline-block mt-6 mr-5 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Редагувати</a>
                <a href="{% url 'item:delete_item' item.pk %}" class="inline-block mt-6  px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Видалити</a>
            {% else %}
                <p>Дізнатись більше про продавця</p>
                <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">{{ item.owner }}</a>
            {% endif %}
        </div>
    </div>
  </div>

  {% if related_items %}
  <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Схожі товари</h2>
    <div class="grid grid-cols-4 gap-3">
      {% for item in related_items %}
        <div>
          <a href="{% url 'item:detail' item.pk %}">
            <div>
              {% if item.image %}
                <img src="{{ item.image.url }}" class="rounded-t-xl" alt="">
              {% else %}
                <img src="" class="rounded-t-xl" alt="Тут мало б бути зображення цього товару" style="display: inline-block;">
              {% endif %}
            </div>
            <div class="p-6 bg-white rounded-b-xl">
              <h2 class="text-xl ">{{ item.name }}</h2>
              <p class="text-gray-500">Price: {{ item.price }} грн.</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
  {% endif %}
{% endblock %}

main/items/templates/items/form.html
{% extends 'marketplace/base.html' %}

{% block content %}
  <div class="w-1/4 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">{{ title }}</h1>
    <form method="post" action="." enctype="multipart/form-data">
      {% csrf_token %}
      <div class="space-y-4">
        {{ form.as_p }}
      </div>

      {% if form.errors or form.non_field_errors %}
          <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
              {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
          </div>
        {% endif %}
      <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
  </div>
{% endblock %}

main/items/templates/items/searched_items.html
{% extends 'marketplace/base.html' %}

{% block content %}
  <div class="pb-6 grid grid-cols-4 gap-6 ">
    <div class="col-span-1 bg-gray-100 rounded-xl">
      <form method="get" action="{% url 'item:searched_items' %}">
        <input name="query" class="m-2 p-3 border rounded-xl" type="text" value="{{ query }}" style="width:96%">

        <button class="m-2 py-3 px-8 text-lg bg-teal-500 text-white rounded-xl">Пошук</button>
      </form>

      <hr class="my-6">
      <p class="ml-2 font-semibold">Категорії</p>
      <ul>
        {% for category in categories %}
        <li class="ml-2 py-2 px-2 rounded-xl {% if category.pk == category_id %}bg-gray-200{% endif %}">
          <a href="{% url 'item:searched_items' %}?query={{ query }}&category={{ category.pk }}">{{ category.name }}</a>
        </li>
        {% endfor %}
      </ul>
      <hr class="my-6">
      <p class="font-semibold ml-2">Скинути фільтри</p>
      <ul>
        <li><a href="{% url 'item:searched_items' %}" class="mt-2 ml-2 py-3 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Скинути</a></li>
      </ul>
    </div>
    <div class="col-span-3 bg-gray-100 rounded-xl">
      <div class="grid grid-cols-3 gap-3">
      {% for item in items %}
        <div>
          <a href="{% url 'item:detail' item.pk %}">
            <div>
              {% if item.image %}
                <img src="{{ item.image.url }}" class="rounded-t-xl" alt="" style="max-height: 453.75px; max-width: 453.75px">
              {% else %}
                <img src="" class="rounded-t-xl" alt="Тут мало б бути зображення цього товару" style="display: block; height: 442.75px; width: 442.75px">
              {% endif %}
            </div>
            <div class="p-6 bg-white rounded-b-xl">
              <h2 class="text-xl ">{{ item.name }}</h2>
              <p class="text-gray-500">Price: {{ item.price }} грн.</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
    </div>
  </div>

{% endblock %}

main/marketplace/templates/marketplace/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>MyMarketplace</title>
</head>
<body>
    <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">MyMarketplace</a>

        <div class="space-x-6">
        <a href="{% url 'item:new_item' %}" class="text-lg font-semibold hover:text-gray-500">Додати пердмет</a>
        <a href="{% url 'item:searched_items' %}" class="text-lg font-semibold hover:text-gray-500">Пошук</a>

        {% if request.user.is_authenticated %}
            <a href="{% url 'dashboard:owner_stuff' %}" class="px-4 py-2 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Ваші предмети</a>
            <a href="{% url 'marketplace:logout' %}" class="px-4 py-2 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Вийти</a>
        {% else %}
            <a href="{% url 'marketplace:signup' %}" class="px-4 py-2 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Зареєструватись</a>
            <a href="{% url 'marketplace:login' %}" class="px-4 py-2 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Увійти</a>
        {% endif %}
        </div>
    </nav>



    <div class="px-6 py-6" style="min-height:calc(100vh - 213px)">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="px-4 py-2 flex justify-between bg-gray-800">
        <div class="w-2/4 pr-10">
            <h3 class="mb-2 font-semibold text-gray-400">MyMarketplace</h3>
            <p class="text-sm text-gray-500">Усі онлайн-оголошення України тут. У нас ви знайдете те, що шукали!
                Ви зможете розмістити оголошення на будь-яку тематику легко й швидко. За допомогою нашого сервісу ви
                зможете купити чи продати з рук у руки практично все, що завгодно.</p>
            <p class="text-sm text-gray-500">Всі права захищені.</p>
            <p class="text-sm text-gray-500">MyMarketplace працює на основі Python.</p>
        </div>

        <div class="w-1/4" style="text-align: right;">
            <h3 class="mb-2 font-semibold text-gray-400">Меню</h3>
            <ul class="space-y-2">
                <li><a href="#" class="text-sm text-teal-500 hover:text-teal-700">Про нас</a></li>
                <li><a href="#" class="text-sm text-teal-500 hover:text-teal-700">Контакти</a></li>
                <li><a href="#" class="text-sm text-teal-500 hover:text-teal-700">Політика компанії</a></li>
            </ul>
        </div>
    </footer>

</body>
</html>

main/marketplace/templates/marketplace/index.html
{% extends 'marketplace/base.html' %}

{% block content %}
  <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Усі товари</h2>
    <div class="grid grid-cols-4 gap-3">
      {% for item in items %}
        <div>
          <a href="{% url 'item:detail' item.pk %}">
            <div>
              {% if item.image %}
                <img src="{{ item.image.url }}" class="rounded-t-xl" alt="" style="max-height: 442.75px; max-width: 442.75px">
              {% else %}
                <img src="" class="rounded-t-xl" alt="Тут мало б бути зображення цього товару" style="display: block; height: 442.75px; width: 442.75px">
              {% endif %}
            </div>
            <div class="p-6 bg-white rounded-b-xl">
              <h2 class="text-xl ">{{ item.name }}</h2>
              <p class="text-gray-500">Price: {{ item.price }} грн.</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>

  <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Категорії</h2>
    <div class="grid grid-cols-8 gap-3">
      {% for category in categories %}
        <div>
          <div class="p-3 bg-white rounded-b-xl" style="text-align: center;">
            <h2 class="text-xl ">{{ category.name }}</h2>
            <p class="text-gray-500">{{ category.items.count }} items</p>
          </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

main/marketplace/templates/marketplace/login.html
{% extends 'marketplace/base.html' %}

{% block content %}
  <div class="w-1/4 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Увійти</h1>

    <form method="post" action=".">
      {% csrf_token %}

      <div class="mb-3">
        <label class="inline-block mb-2">Ім'я</label><br>
        {{ form.username }}
      </div>

      <div class="mb-3">
        <label class="inline-block mb-2">Пароль</label><br>
        {{ form.password }}
      </div>

      {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
          {% for field in form %}
            {{ field.errors }}
          {% endfor %}

          {{ form.non_field_errors }}
        </div>
      {% endif %}
      <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Підтвердити</button>
    </form>
  </div>
{% endblock %}

main/marketplace/templates/marketplace/signup.html
{% extends 'marketplace/base.html' %}

{% block content %}
  <div class="w-1/4 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Зареєструватись</h1>

    <form method="post" action=".">
      {% csrf_token %}

      <div class="mb-3">
        <label class="inline-block mb-2">Ім'я</label><br>
        {{ form.username }}
      </div>

      <div class="mb-3">
        <label class="inline-block mb-2">Електронна адреса</label><br>
        {{ form.email }}
      </div>

      <div class="mb-3">
        <label class="inline-block mb-2">Пароль</label><br>
        {{ form.password1 }}
      </div>

      <div class="mb-3">
        <label class="inline-block mb-2">Повторіть пароль</label><br>
        {{ form.password2 }}
      </div>

      {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
          {% for field in form %}
            {{ field.errors }}
          {% endfor %}

          {{ form.non_field_errors }}
        </div>
      {% endif %}
      <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Підтвердити</button>
    </form>
  </div>
{% endblock %}